### ISSUE TITLE
Check if deployment branch can be the newest tag

### ISSUE THREAD

**Issue by eugenk** [ontohub/deployment#3]
We specify a branch which shall be deployed to a server. Check if this can be replaced by "the latest tag".

**Comment by phyrog** [comment]
Here is a way to deploy the latest tag: https://nathanhoad.net/deploy-from-a-git-tag-with-capistrano

**Comment by eugenk** [comment]
Unfortunately, this does not work because it checks for the latest tag in the current repository, which is `deployment` and not, for instance, `ontohub-backend`. This is a little bit more complicated: We need to find the latest tag from the repository that is checked out on the server. Not impossible, but more involved.
