### ISSUE TITLE
Deployment does not use up to date frontend config

### ISSUE THREAD

**Issue by phyrog** [ontohub/deployment#5]
The file `config/environment.js` is not updated during deployment. This seems to be the problem with the current login issues on `tb`, as the `ember-simple-auth-token` and `ember-simple-auth` config blocks are missing.

Ping @eugenk

**Comment by eugenk** [comment]
What should we do with the `environment.js` when we deploy? I thought of this as a configuration file that should not be changed.

**Comment by phyrog** [comment]
It is a configuration file, but unfortunately not only for the app, but also for its dependencies, so we need it up to date. I don't expect there to be many (if any) host specific settings in there, so we probably don't need to change anything there on the host.

**Comment by eugenk** [comment]
I deployed again from the branch `deployment_does_not_use_up_to_date_frontend_config` 
 [(compare to master)](https://github.com/ontohub/deployment/compare/5-deployment_does_not_use_up_to_date_frontend_config) but the login still does not work:
```
Request URL:https://tb.iks.cs.ovgu.de/undefined/users/sign_in
Request Method:POST
Status Code:404 Not Found
```

**Comment by phyrog** [comment]
I already fixed this on the mirage config branch, but I'll extract it to another pull request. It's not related to deployment

**Comment by eugenk** [comment]
Ok. Then I'm going to send a pull request on deployment now.
